# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title-bold: JEST
title-normal: Junior Enterprise for Science and Tech
title: JEST - Junior Enterprise for Science and Tech
email: geral@jest.pt
description: Providing data-based solutions for life sciences
baseurl: "/jestpt.github.io" # the subpath of your site, e.g. /blog
url: "http://jest.pt" # the base hostname & protocol for your site
author: João Coelho
street_address: Department of Life Sciences
city: Coimbra
zip_code: 3000-406
country: Portugal
phone: +351 966 739 005

# Plugins
gems:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jemoji

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages" 
tiles-count: 6

# Social settings
500px_url: 
facebook_url: https://www.facebook.com/UC.JEST/
github_url: 
gitlab_url: 
googleplus_url: 
instagram_url: https://www.instagram.com/jest_fctuc/
linkedin_url: 
pinterest_url: 
slack_url: 
twitter_url: 

# Build settings
markdown: kramdown

# Plugin: jekyll-seo-tag
twitter:
  username: 
# Add one or more of the following
facebook:
  app_id: 
  publisher: 
  admins: 
logo:
google_site_verification: 

encoding: UTF-8